
site_name: Docs


theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  search: true
  features:
    - quick-links
    - navigation
    - search
    - toc
    - fullscreen
    - bookmarks
    - tabs
    - code
    - edit-on-github
    - language-selector
    - code
    - cover
    - footer
    - social-share
    - theme-switcher
nav:
  - Home: index.md
  
  - Types:
    - alias EventHandler : types/EventHandler.md
    - alias EventName : types/EventName.md
    - alias Point3F : types/Point3F.md
    - alias QuatF : types/QuatF.md
    - class Box3F : types/Box3F.md
    - class MatrixF : types/MatrixF.md
    - class OrientedBox3F : types/OrientedBox3F.md
    - class SceneObject : types/SceneObject.md
    - class Sim : types/Sim.md
    - class SimGroup : types/SimGroup.md
    - class SimObject : types/SimObject.md
    - class SimSet : types/SimSet.md
    - class TorqueScript : types/TorqueScript.md
    - class UI : types/UI.md
    - class be : types/be.md
    - class controller : types/controller.md
    - class core : types/core.md
    - class engine : types/engine.md
    - class extensions : types/extensions.md
    - class guihooks : types/guihooks.md
    - class input : types/input.md
    - class map : types/map.md
    - class obj : types/obj.md
    - class particles : types/particles.md
    - class player : types/player.md
    - class profiler : types/profiler.md
    - class quat : types/quat.md
    - class render : types/render.md
    - class scenario : types/scenario.md
    - class scenetree : types/scenetree.md
    - class settings : types/settings.md
    - class sound : types/sound.md
    - class spawn : types/spawn.md
    - class vec3 : types/vec3.md
    - class vehicle : types/vehicle.md
    
  
  
  - Modules:
    - _sceneobject : modules/_sceneobject.md
    - _simgroup : modules/_simgroup.md
    - _simobject : modules/_simobject.md
    - _simset : modules/_simset.md
    
  
  
  - Globals:
    - AddEventHandler : globals/AddEventHandler.md
    - Box3F : globals/Box3F.md
    - MatrixF : globals/MatrixF.md
    - OrientedBox3F : globals/OrientedBox3F.md
    - SimGroup : globals/SimGroup.md
    - SimSet : globals/SimSet.md
    - TriggerServerEvent : globals/TriggerServerEvent.md
    - createObject : globals/createObject.md
    - jsonDecode : globals/jsonDecode.md
    - quat : globals/quat.md
    - setExtensionUnloadMode : globals/setExtensionUnloadMode.md
    - vec3 : globals/vec3.md
    
  
extra:
  footer: ""
